export const styles = {
  app: {
    // display: 'flex',
    // flexDirection: 'column' as 'column',
    // alignItems: 'center',
    // justifyContent: 'center',
    width: '100vw',
    height: '100vh',
  },
  container: {
    border: '1px solid rgb(155,155,155)',
    width: 40,
    height: 50,
    margin: 5,
    fontSize: 30,
    display: 'flex',
    textAlign: 'center' as 'center',
    justifyContent: 'center',
    alignItems: 'center',
    boxShadow: '1px 1px 2px 2px rgba(55,55,55,0.1)',
  },
  wrapper: {
    display: 'flex',
    flexDirection: 'row' as 'row',
    margin: '0 auto',
  },
  keyboardContainer: {
    position: 'absolute' as 'absolute',
    bottom: 20,
    width: '100%',
    display: 'flex',
    alighItems: 'center',

  },
  guessesWrapper: {
    height: '380px',
    maxHeight: '50vh',
    overflowY: 'scroll' as 'scroll',
    width: '100%',
    display: 'flex',
    flexDirection: 'column' as 'column',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  bravoPopup: {
    position: 'absolute' as 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    backgroundColor: 'white',
    borderRadius: '5px',
    padding: '10px',
    boxShadow: '1px 1px 2px 2px rgba(55,55,55,0.1)',
    display: 'flex',
    flexDirection: 'column' as 'column',
    justifyContent: 'center',
    alignItems: 'center',
    width: '80vw',
    height: '60vh',
    maxWidth: '600px',
    maxHeight: '600px',
    zIndex: 100,
  },
  betaBanner: {
    position: 'absolute' as 'absolute',
    top: -55,
    right: -65,
    fotnSize: 50,
    fontWeight: 'bold',
    color: 'red',
    width: "0",
    height: "0",
    borderLeft: "100px solid transparent",
    borderRight: "100px solid transparent",
    borderBottom: "100px solid rgba(245, 39, 78, 0.4)",
    transform: 'rotate(45deg)',

  },
  betaText: {
    position: 'absolute' as 'absolute',
    top: 18,
    right: 8,
    fontSize: 28,
    fontWeight: 'bold',
    color: 'red',
    transform: 'rotate(45deg)',
  },
  randomSwitch: {
    position: 'absolute' as 'absolute',
    top: 0,
    left: 0,
    backgroundColor: 'white',
    fotnSize: 20,
    padding: '5px',
    cursor: 'pointer',
  },
  explanerWindow: {
    boxSizing: 'border-box' as 'border-box',
    width: '100vw',
    height: '100vh',
    backgroundColor: 'white',
    position: 'absolute' as 'absolute',
    top: 0,
    left: 0,
    zIndex: 100,
    display: 'flex',
    flexDirection: 'column' as 'column',
    paddingTop: '40px',
    alignItems: 'center',
  },
  greebButton: {
    backgroundColor: '#6ff573',
    borderRadius: '5px',
    padding: '5px',
    margin: '5px',
    cursor: 'pointer',
    width: '100px',
    height: '50px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',

  },
}